---
title: "Kikwit Ebola Analysis"
output: html_document
---
**Disclaimer: ** tutorial in progress.


1. Load library and data
```{r}
# load the ABSEIR library
library(ABSEIR)
# read in the data set
data(Kikwit1995)
```


2. Plot cases
```{r}
# make barplot of new case counts
barplot(t(Kikwit1995$Count), main = "New Cases", xlab = "Day", ylab = "Cases")
# add an X axis to give a reference epidemic time
axis(side = 1, at = seq(0, nrow(Kikwit1995), 50)) 
```

3. Build model

```{r}
# Create a model to relate observe data to epidemic process
data_model = DataModel(Kikwit1995$Count,
                       type = "identity",
                       compartment="I_star",
                       cumulative=FALSE)
# Create a model to describe relationship of any covariates to epidemic intensity
exposure_model_1 = ExposureModel(matrix(1, nrow = nrow(Kikwit1995)),
                                nTpt = nrow(Kikwit1995),
                                nLoc = 1,
                                betaPriorPrecision = 0.5,
                                betaPriorMean = 0)
# Create a (more realistic) Model to describe relationship of any covariates to epidemic intensity
# In this analysis we know on which date interventions began, so we may include a linear term
# starting on that date. 
intervention_term = cumsum(Kikwit1995$Date >  as.Date("05-09-1995", "%m-%d-%Y"))
intervention_term = intervention_term/max(intervention_term)
exposure_model_2 = ExposureModel(cbind(1,intervention_term),
                                nTpt = nrow(Kikwit1995),
                                nLoc = 1,
                                betaPriorPrecision = 0.5,
                                betaPriorMean = 0)
# There's no reinfection in this case, so we just use a "SEIR" model. 
reinfection_model = ReinfectionModel("SEIR")
# we have no distance model, because it's a non-spatial analysis, but we still
# need to create an empty DistanceModel for ABSEIR. This approach is a bit clunky, 
# so we're open to suggestions. One option may be the implmentation of new verisons
# of the qSEIR functions included in libSpatialSEIR. 
distance_model = DistanceModel(list(matrix(0)))

# Set initial population sizes
initial_value_container = InitialValueContainer(S0=5.36e6,
                                                E0=2,
                                                I0=2,
                                                R0=0)
  
  
# Model to describe E to I and I to R transition probabilities. Prior values from 
# Lekone and Finkenstadt 2006
# This is going to be expanded soon, so that we won't need to rely on 
# the exponential assumption
transition_priors = TransitionPriors(p_ei = 1-exp(-1/5), 
                                     p_ir= 1-exp(-1/7),
                                     p_ei_ess = 100,
                                     p_ir_ess = 100)

# Set algorithm configuration
sampling_control = SamplingControl(seed = 123123, 
                                   n_cores = 2,
                                   algorithm="Beaumont2009",
                                    list(batch_size = 10000,
                                           epochs = 1e6,
                                           max_batches = 10,
                                           shrinkage = 0.99,
                                           multivariate_perturbation=TRUE
                                         )
                                   )


```

4. Run our two models

```{r}

result1 = SpatialSEIRModel(data_model,
                          exposure_model_1,
                          reinfection_model,
                          distance_model,
                          transition_priors,
                          initial_value_container,
                          sampling_control,
                          samples = 100,
                          verbose = FALSE)

result2 = SpatialSEIRModel(data_model,
                          exposure_model_2,
                          reinfection_model,
                          distance_model,
                          transition_priors,
                          initial_value_container,
                          sampling_control,
                          samples = 100,
                          verbose = FALSE)


```

5. Compare the two models, and consider a summary of their parameter estimates

```{r}
compareModels(result1, result2, n_samples = 10000, 
              batch_size = 20000)

summary(result1)

summary(result2)


```


6. Consider model fit by looking at posterior predictive distribution of epidemic values. 

```{r}
# Simulate new epidemics based on the accepted parameters for model 1
simulated1 = epidemic.simulations(result1, replicates = 25)

allSimulatedI_star = sapply(simulated1$simulationResults, function(x){x$I_star})


lowerQuantile = apply(allSimulatedI_star, 1, quantile, probs = c(0.025))
posteriorMean = apply(allSimulatedI_star, 1, mean)
upperQuantile = apply(allSimulatedI_star, 1, quantile, probs = c(0.975))


plot(Kikwit1995$Count, ylim = c(0, max(Kikwit1995$Count)*1.2),
     xlab = "Epidemic Day", ylab = "New Cases", main = "Model 1: Posterior Predictive Distribution")
lines(upperQuantile, lty = 2, col = "blue")
lines(lowerQuantile, lty = 2, col = "blue")
lines(posteriorMean, lty = 1, col = "blue")

legend(x = 100, y = 12, legend = c("Mean", "95% CI", "Observed"), lty = c(1,2,0), 
       pch = c(NA,NA,1), col = c("blue", "blue", "black"), cex = 1)
```

```{r}
# Simulate new epidemics based on the accepted parameters for model 2
simulated2 = epidemic.simulations(result2, replicates = 25)

allSimulatedI_star = sapply(simulated2$simulationResults, function(x){x$I_star})


lowerQuantile = apply(allSimulatedI_star, 1, quantile, probs = c(0.025))
posteriorMean = apply(allSimulatedI_star, 1, mean)
upperQuantile = apply(allSimulatedI_star, 1, quantile, probs = c(0.975))


plot(Kikwit1995$Count, ylim = c(0, max(Kikwit1995$Count)*1.2),
     xlab = "Epidemic Day", ylab = "New Cases", main = "Model 2: Posterior Predictive Distribution")
lines(upperQuantile, lty = 2, col = "blue")
lines(lowerQuantile, lty = 2, col = "blue")
lines(posteriorMean, lty = 1, col = "blue")

legend(x = 100, y = 12, legend = c("Mean", "95% CI", "Observed"), lty = c(1,2,0), 
       pch = c(NA,NA,1), col = c("blue", "blue", "black"), cex = 1)
```

7. Look at reproductive number estimates

```{r}
allSimulatedR0_1 = sapply(simulated1$simulationResults, function(x){x$R0t})
allSimulatedEA_R0_1 = sapply(simulated1$simulationResults, function(x){x$R_EA})

allSimulatedR0_2 = sapply(simulated2$simulationResults, function(x){x$R0t})
allSimulatedEA_R0_2 = sapply(simulated2$simulationResults, function(x){x$R_EA})

par(mfrow = c(1,2))
plot(apply(allSimulatedR0_1, 1, median), type = "l", ylim = c(0, 1.5), lwd =2,
     ylab = "Reproductive Number", main = "Model 1: R0(t) and EA-R(t)")
lines(apply(allSimulatedEA_R0_1, 1, median), lwd = 2, lty = 2, col = "blue")

plot(apply(allSimulatedR0_2, 1, median), type = "l", ylim = c(0, 1.5), lwd = 2,
     ylab = "Reproductive Number", main = "Model 2: R0(t) and EA-R(t)")
lines(apply(allSimulatedEA_R0_2, 1, median), lwd =2, lty = 2, col = "blue")
legend(x = 130, y = 1.25, lty = c(1,2), col = c(1,4), legend = c("R0(t)", "EA-R(t)"),
       lwd = c(2,2), cex = 1.25)
  

```
