// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// calculate_weights
Eigen::VectorXd calculate_weights(double cur_e, double prev_e, Eigen::MatrixXd eps, Eigen::VectorXd prev_wts);
RcppExport SEXP ABSEIR_calculate_weights(SEXP cur_eSEXP, SEXP prev_eSEXP, SEXP epsSEXP, SEXP prev_wtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type cur_e(cur_eSEXP);
    Rcpp::traits::input_parameter< double >::type prev_e(prev_eSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type prev_wts(prev_wtsSEXP);
    __result = Rcpp::wrap(calculate_weights(cur_e, prev_e, eps, prev_wts));
    return __result;
END_RCPP
}
// solve_for_epsilon
double solve_for_epsilon(double LB, double UB, double prev_e, double alpha, Eigen::MatrixXd eps, Eigen::VectorXd prev_wts);
RcppExport SEXP ABSEIR_solve_for_epsilon(SEXP LBSEXP, SEXP UBSEXP, SEXP prev_eSEXP, SEXP alphaSEXP, SEXP epsSEXP, SEXP prev_wtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type LB(LBSEXP);
    Rcpp::traits::input_parameter< double >::type UB(UBSEXP);
    Rcpp::traits::input_parameter< double >::type prev_e(prev_eSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type prev_wts(prev_wtsSEXP);
    __result = Rcpp::wrap(solve_for_epsilon(LB, UB, prev_e, alpha, eps, prev_wts));
    return __result;
END_RCPP
}
