# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_weights <- function(cur_e, prev_e, eps, prev_wts) {
    .Call('ABSEIR_calculate_weights', PACKAGE = 'ABSEIR', cur_e, prev_e, eps, prev_wts)
}

solve_for_epsilon <- function(LB, UB, prev_e, alpha, eps, prev_wts) {
    .Call('ABSEIR_solve_for_epsilon', PACKAGE = 'ABSEIR', LB, UB, prev_e, alpha, eps, prev_wts)
}

